- name: install tomcat server
  hosts: target-2
  become: true
  vars:  # bu vars hissesinde yalniz .yml faylinda butun variable leri teyin edirem ve asagidaki tasklara elave edirem 
    - tomcat_url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz
    - tomcat_package: apache-tomcat-8.5.61
  tasks:
    - name: install java
      yum:
        name: java
        state: latest

    - name: download tomcat server packages
      get_url:
        url: "{{ tomcat_url }}"
        dest: /opt

    - name: extract tomcat packages
      unarchive:
        src: /opt/{{ tomcat_package }}.tar.gz
        dest: /opt
        remote_src: yes

    - name: start tomcat services
      shell: nohup /opt/{{ tomcat_package }}/bin/startup.sh