- name: install tomcat server
  hosts: all
  become: true
  vars_files:  # bu hissedeki vars_files gedir variableleri asagida qeyd olunan tomcat_vars direktoriyasindan goturur. (tomcat_vars direktoriyasi yml fali olanda yerin yanindadir) Asagida qeyd olunan tasklar da ise deyisen olaraq qeyd olunur. Lazim olan deyisenleri tomcat_vars dir-dan goturur
    - tomcat_vars

  tasks:
    - name: install java
      yum:
        name: java
        state: latest

    - name: download tomcat server packages
      get_url:
        url: "{{ tomcat_url }}"
        dest: /opt

    - name: extract tomcat packages
      unarchive:
        src: /opt/{{ tomcat_package }}.tar.gz
        dest: /opt
        remote_src: yes

    - name: start tomcat services
      shell: nohup /opt/{{ tomcat_package }}/bin/startup.sh