- name: Templata jinja2 examples
  hosts: target-1
  vars:
    env: staging
    my_app_version: v1.1
  tasks:
    - name: Template file into remote hosts
      template:
        src: "{{ item }}.j2"
        dest: "/etc/{{ item }}"
        owner: murad
        group: project
        mode: 0775
      become: true
      loop:
        - my_app.conf
        - my_app-release

