    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: "{{ datacenter }}"
        folder: /{{ datacenter }}/vm
        guest_id: centos64Guest
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        disk:
          - size: 25gb
            type: eagerzeroedthick
            state: present
            datastore: "{{ datastore }}"
        networks:
          - name: VM Network
            ip: 10.10.45.201
            netmask: 255.255.255.0
            gateway: 10.10.45.254
            type: static
#            domain: isbis.local
#            dns_servers:
#              - 8.8.8.8
        customization:
          domain: test.local
          dns_servers:
            - 8.8.8.8
            - 8.8.4.4
        hardware:
          memory: 2gb
          num_cpus: 1
          hotadd_cpu: True
         wait_for_ip_address: True
        state: poweredon
      delegate_to: localhost