- name: Deploy a web application
  hosts: target-2
  vars_files:
    - group_vars/db_and_web_servers.yml
  tasks: 
    - name: Install all required dependencies
      apt: name="{{ item }}" state=installed
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential 
        - python-pip 
        - python-mysqldb

    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml



